# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    album_manager:
        class: AppBundle\Service\AlbumManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    image_manager:
        class: AppBundle\Service\ImageManager
        arguments: [ "@doctrine.orm.entity_manager", "@knp_paginator" ]

    serializer_proxy:
        class: AppBundle\Service\SerializerProxy
        arguments: [ "@jms_serializer", "json" ]

    pagination_renderer:
        class: AppBundle\Service\PaginationRenderer
        arguments: [ "@knp_paginator.twig.extension.pagination", "@twig" ]
